import type {Metadata} from 'next';
import Image from 'next/image';
import {PostCard} from '@/components/PostCard';
import {Rating} from '@/components/Rating';
import {StoreActions} from '@/components/StoreActions';
import {getStore} from '@/lib/server-api';

type Props={params:Promise<{id:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {id}=await params;const {store}=await getStore(id);return {title:store.name,description:store.localized_description??`${store.name} community reviews`}}
export default async function Page({params}:Props){const {id}=await params;const {store,recent_posts}=await getStore(id);return <main className="store-page"><section className="store-hero-grid"><div className="store-main-image"><Image src="/images/store-detail.jpg" fill style={{objectFit:'cover'}} sizes="(max-width: 760px) 100vw, 70vw" priority alt={`Interior at ${store.name}`}/></div><div className="store-side-image"><Image src="/images/store-lighting.jpg" fill style={{objectFit:'cover'}} sizes="30vw" alt={`Lighting selection at ${store.name}`}/></div></section><section className="store-overview"><div className="store-copy"><p className="eyebrow">{store.category_labels.join(' · ')}</p><h1>{store.name}</h1><p>{store.district}, {store.city} · {((store.distance_meters??0)/1000).toLocaleString('tr',{maximumFractionDigits:1})} km</p></div><div className="store-score"><span>Boşa Gezme!</span><strong><Rating value={store.platform.average_rating}/></strong><small>{store.platform.review_count} reviews</small></div><div className="store-score"><span>Saved by</span><strong>{store.platform.favorite_count}</strong><small>people</small></div><StoreActions/></section><section className="store-body"><div className="store-description"><p className="eyebrow">About this store</p><h2>Should you actually go there?</h2><p>{store.localized_description}</p><address>{store.address}, {store.district}/{store.city}</address><div className="external-note"><strong>Google Maps</strong><span>External source information is kept separate from Boşa Gezme! community ratings.</span></div></div><div className="store-reviews"><p className="eyebrow">Community experiences</p>{recent_posts.length?recent_posts.map(p=><PostCard post={p} key={p.id}/>):<div className="empty-state"><h2>No community reviews yet.</h2><p>Visited this store? Be the first to share your experience.</p></div>}</div></section></main>}
