import type {Metadata} from 'next';import {Onest} from 'next/font/google';import {Header} from '@/components/Header';import {SessionKeeper} from '@/components/SessionKeeper';import {SiteFooter} from '@/components/SiteFooter';import {I18nProvider} from '@/i18n/I18nProvider';import type {Locale} from '@/lib/types';import '../../globals.css';import '../../daylight.css';
// One family for the whole product. Onest carries Latin, Latin Extended and Cyrillic,
// which the four shipped locales require -- see DESIGN.md before replacing it.
const sans=Onest({variable:'--font-sans',subsets:['latin','latin-ext','cyrillic'],display:'swap'});
import {asLocale,canonicalFor,locales,shareImage,shareTitle,siteUrl} from '@/lib/site';
const metadataCopy:Record<Locale,{title:string;description:string}>={
  tr:{title:'Boşa Gezme! Bize Sor. — Gerçek mağazalar, gerçek deneyimler',description:'Boşa Gezme!, gerçek ev ve yaşam mağazalarını değerlendirmeye yarayan bir topluluk platformudur.'},
  en:{title:'Boşa Gezme! Bize Sor. — Real stores, real experiences',description:'Boşa Gezme! is a community platform for reviewing real home and living stores.'},
  de:{title:'Boşa Gezme! Bize Sor. — Echte Geschäfte, echte Erlebnisse',description:'Boşa Gezme! ist eine Community-Plattform für Bewertungen echter Wohn- und Einrichtungsgeschäfte.'},
  ru:{title:'Boşa Gezme! Bize Sor. — Настоящие магазины, реальные впечатления',description:'Boşa Gezme! — сообщество, где оценивают настоящие магазины товаров для дома.'},
};
// Every language is a real URL now, so the root can carry the site wide hreflang set for
// the homepage. Child routes state their own.
export function generateStaticParams(){return locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const locale=asLocale((await params).locale);const copy=metadataCopy[locale];return {metadataBase:new URL(siteUrl),applicationName:'Boşa Gezme!',alternates:canonicalFor(locale,'/'),title:{default:copy.title,template:'%s | Boşa Gezme!'},description:copy.description,openGraph:{type:'website',siteName:'Boşa Gezme!',images:[shareImage],title:shareTitle,description:copy.description},twitter:{card:'summary_large_image',title:shareTitle,description:copy.description,images:[shareImage.url]}};}
export default async function RootLayout({children,params}:{children:React.ReactNode;params:Promise<{locale:string}>}){const locale=asLocale((await params).locale);return <html lang={locale} className={sans.variable}><body>{/* IMPECCABLE · THESIS: Boşa Gezme! is daylight entering a home and making things clearer, not a poster and not a card grid. OWN-WORLD: warm off-white ground, near-black ink, one honey accent used in calm areas, clay for the values that must be read first; one family, generous space, soft geometry. STORY: real visits lead, source context stays legible, and every path helps someone decide whether a physical trip is worthwhile. FIRST VIEWPORT: compact masthead above a split editorial intro and a full-width photographic dispatch; discovery remains one tap away. FORM: Daylight. FINISH: unreviewed and undocumented is unfinished; DESIGN.md is the authority and every screen answers its checks */}<I18nProvider initialLocale={locale}><SessionKeeper/><Header/>{children}<SiteFooter locale={locale}/></I18nProvider></body></html>}
