'use client';
import {FormEvent,useState} from 'react';
import {X} from 'lucide-react';
import {useI18n} from '@/i18n/I18nProvider';

export function AuthDialog({open,onClose}:{open:boolean;onClose:()=>void}){
  const {t,locale}=useI18n();const [emailMode,setEmailMode]=useState(false);const [sent,setSent]=useState(false);const [email,setEmail]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  if(!open)return null;
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch(sent?'/api/auth/verify-code':'/api/auth/request-code',{method:'POST',headers:{'content-type':'application/json','x-locale':locale},body:JSON.stringify(sent?{email,code}:{email})});if(!response.ok){const body=await response.json();throw new Error(body?.error?.message??'Request failed')}if(sent)onClose();else setSent(true)}catch(reason){setError(reason instanceof Error?reason.message:'Request failed')}finally{setBusy(false)}}
  return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="auth-dialog" role="dialog" aria-modal="true" aria-labelledby="auth-title" onMouseDown={e=>e.stopPropagation()}><button className="icon-button dialog-close" onClick={onClose} aria-label={t('close')}><X/></button><p className="eyebrow">{t('wordmark')}</p><h2 id="auth-title">{emailMode?(sent?'Verification code':t('email')):t('signInTitle')}</h2>{emailMode?<form onSubmit={submit}><label><span>{sent?'6-digit code':t('email')}</span><input required value={sent?code:email} onChange={e=>sent?setCode(e.target.value.replace(/\D/g,'').slice(0,6)):setEmail(e.target.value)} type={sent?'text':'email'} inputMode={sent?'numeric':'email'} maxLength={sent?6:254} placeholder={sent?'000000':'name@example.com'}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy||(sent&&code.length!==6)} className="button primary" type="submit">{busy?'…':sent?'Verify':t('email')}</button></form>:<><p>Keep your saved stores and contributions with you across devices.</p><button className="button primary" title="Requires a configured Google web client">{t('google')}</button><button className="button secondary" onClick={()=>setEmailMode(true)}>{t('email')}</button><button className="button quiet" onClick={onClose}>{t('later')}</button></>}</section></div>
}
