import type {Metadata} from 'next';import {Onest,Unbounded} from 'next/font/google';import {Header} from '@/components/Header';import {I18nProvider} from '@/i18n/I18nProvider';import type {Locale} from '@/lib/types';import '../globals.css';import '../city-print.css';
const sans=Onest({variable:'--font-sans',subsets:['latin','cyrillic'],display:'swap'});const display=Unbounded({variable:'--font-display',subsets:['latin','cyrillic'],display:'swap'});
import {asLocale,canonicalFor,locales,siteUrl} from '@/lib/site';
const metadataCopy:Record<Locale,{title:string;description:string}>={
  tr:{title:'Boşa Gezme! — Gerçek mağazalar, gerçek deneyimler',description:'Doğrulanmış topluluk ziyaretleriyle gerçek ev ve yaşam mağazalarını keşfet.'},
  en:{title:'Boşa Gezme! — Real stores, real experiences',description:'Discover real physical home and living stores through verified community visits.'},
  de:{title:'Boşa Gezme! — Echte Geschäfte, echte Erlebnisse',description:'Entdecke echte Wohn- und Einrichtungsgeschäfte durch verifizierte Besuche der Community.'},
  ru:{title:'Boşa Gezme! — Настоящие магазины, реальные впечатления',description:'Открывайте настоящие магазины товаров для дома благодаря проверенным визитам сообщества.'},
};
// Every language is a real URL now, so the root can carry the site wide hreflang set for
// the homepage. Child routes state their own.
export function generateStaticParams(){return locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const locale=asLocale((await params).locale);const copy=metadataCopy[locale];return {metadataBase:new URL(siteUrl),applicationName:'Boşa Gezme!',alternates:canonicalFor(locale,'/'),title:{default:copy.title,template:'%s | Boşa Gezme!'},description:copy.description,openGraph:{type:'website',siteName:'Boşa Gezme!',title:copy.title,description:copy.description,images:[{url:'/brand/social-share-banner.png',width:2172,height:724,alt:'Boşa Gezme!'}]},twitter:{card:'summary_large_image',title:copy.title,description:copy.description,images:['/brand/social-share-banner.png']}};}
export default async function RootLayout({children,params}:{children:React.ReactNode;params:Promise<{locale:string}>}){const locale=asLocale((await params).locale);return <html lang={locale} className={`${sans.variable} ${display.variable}`}><body>{/* IMPECCABLE · THESIS: Boşa Gezme! is a living city print, not a beige lifestyle blog or card grid. OWN-WORLD: warm paper, cobalt ink, vermilion, sun yellow and forest green; asymmetric editorial fields, contact-sheet photography and crisp spot-color controls. STORY: real visits lead, source context stays legible, and every path helps someone decide whether a physical trip is worthwhile. FIRST VIEWPORT: compact masthead above a split editorial intro and a full-width photographic dispatch; discovery remains one tap away. FORM: City Print, grounded direction 3, seed 93d9668a. FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, DESIGN.md, and every shipping raster carrying its provenance */}<I18nProvider initialLocale={locale}><Header/>{children}</I18nProvider></body></html>}
